### ISSUE TITLE
EventEmitter memory leak

### ISSUE THREAD

**Issue by akimyonoglu** [namshi/roger#10]
(node) warning: possible EventEmitter memory leak detected. 11 storage-updated listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:179:15)
    at Namespace.<anonymous> (/src/src/socket.js:30:16)
    at Namespace.emit (events.js:107:17)
    at Namespace.emit (/src/node_modules/socket.io/lib/namespace.js:205:10)
    at /src/node_modules/socket.io/lib/namespace.js:172:14
    at process._tickDomainCallback (node.js:381:11)
stream is closed

**Comment by shidhincr** [comment]
@unlucio Any idea how to fix this ?
